### ISSUE TITLE
GitOpscon EU 2021 - Open forum/ social hour

### ISSUE THREAD

**Issue by christianh814** [gitops-working-group/gitops-working-group#103]
We are looking for a platform to host our Open forum/Social hour after the event. Some ideas that have been suggested

* Rambly (no login required)
* Discord/games (eg. Animal Crossing, Among Us)
* Bevy?
* Airmeet?

Things to What requires a new login (not desired) and what’s the benefit of using a non-hopin platform for the social events?

**Comment by christianh814** [comment]
My Personal preference is Rambly, but would like to hear others opinions.

**Comment by roberthstrand** [comment]
Rambly looks fun, haven't tried that yet. Also, not having to log in and easy set up is great. 

Discord is not something I would recommend for temporary situations, and as we already have a presence on the CNCF slack then most of what people do on Discord is covered. Games can be fun as well, but that requires someone to have both _a_ specific game and console. That's just asking for lower turnout.

**Comment by murillodigital** [comment]
+1 on Rambly

**Comment by pensarguet** [comment]
+1 on Rambly

**Comment by christianh814** [comment]
Looks like the consensus is Rambly. 

Rambly also has a capability to play media during this social event. Did we want to have something playing on the virtual screen?

For those who are curious, you can get familiar with the platform [HERE](https://rambly.app/)

**Comment by christianh814** [comment]
Closing. We will be using Rambly and the link will be announced via the CNCF Slack instance for kubecon
