### ISSUE TITLE
Getting involved

### ISSUE THREAD

**Issue by murillodigital** [gitops-working-group/gitops-working-group#11]
Hi all,

We've built a multi-tenant, Kubernetes native CI/CD platform using an all open-source stack and following the GitOps model for a 5G network function software provider, currently used in production by multiple teams in their organization as well as various 5G mobile network operators. One of the bigger challenges in this implementation was enabling GitOps inside air gapped environments.

I'm also building other GitOps focused prototypes looking to lower the level of entry for teams looking to leverage the model for cluster and application management and delivery.

My name is Leonardo Murillo and I'm founder of Cloud Native Architects and CTO at Qwinix, Inc.

**Comment by scottrigby** [comment]
Linking to #38 ➡️ which you may want to follow for participation process updates 🙂

**Comment by scottrigby** [comment]
We can close this now, since Leo is a maintainer of OpenGitOps now, and served as WG chair for some time 😉❤️ Just goes to show that folx can get VERY involved if they so choose!
