### ISSUE TITLE
Video background for recording and day of 

### ISSUE THREAD

**Issue by soschwei** [gitops-working-group/gitops-working-group#118]
optional background for video (zoom like)

**Comment by soschwei** [comment]
@scottrigby can you attach the files, so I can send the designer a brief?

**Comment by scottrigby** [comment]
@soschwei there were some uploaded here https://github.com/gitops-working-group/gitops-working-group/issues/104#issuecomment-822610004, but I believe the text still needs to be adjusted per https://github.com/gitops-working-group/gitops-working-group/issues/104#issuecomment-824337727.
