### ISSUE TITLE
CFP Committee Tracking for GitOpsCon EU 2021

### ISSUE THREAD

**Issue by christianh814** [gitops-working-group/gitops-working-group#119]
# CFP Committee Tracking

This issue is to track the CFP Committee tasks and progress for GitOpsCon EU 2021

## Organize CFP review committee

The following have voluneered to take part. Check mark means confirmed.

- [x] @christianh814 
- [x] @scottrigby 
- [x] @chris-short 
- [x] @murillodigital 
- [x] @roberthstrand 
- [x] @schlomo
- [x] @tonit 
- [x] @cdavisafc 
- [x] @pensarguet
~- [ ] @mewzherder~

## Grant permissions to CFP form to reviewing committee.

We have a form up on https://bit.ly/gitopscon-2021-cfp @murillodigital  will grant permissions to those who need/want to see it

## Acceptance Criteria

Decide on an acceptance criteria. @murillodigital has a [rough draft](https://docs.google.com/document/d/14eHgAjFvbjRUMDl6uHX3bb1DQJvxRu6ddQPFX-e-wfY/edit) ping him if you need access.

## Review CFPs

Review and Chose Talks/Lightning taks after April 16th. This needs to be done the week of the 19th.

## Send out acceptence notification

Create proposal acceptance template including recording instructions, etc.

**Comment by scottrigby** [comment]
For transparency:

- Is this the full list of people helping with CFPs?
- So far we've followed the plan to add people helping to organize GitOpsCon to the `gitopscon-eu-2021` GH team. I can add people once they're confirmed, and use this issue to track it

**Comment by pensarguet** [comment]
Hi team, congrats for all your work here!

As shared with Cornelia and Tamao, if you need some help to review CFPs, I would be happy to be with you.
Best,
Philippe

**Comment by christianh814** [comment]
@scottrigby can you invite @pensarguet to the meeting?

**Comment by schlomo** [comment]
I am in

**Comment by tonit** [comment]
> For transparency:
> 
> * Is this the full list of people helping with CFPs?
> * So far we've followed the plan to add people helping to organize GitOpsCon to the `gitopscon-eu-2021` GH team. I can add people once they're confirmed, and use this issue to track it

I'd once again offer my help reviewing CFPs. Did it in slack some time ago but i think it got lost..

**Comment by christianh814** [comment]
@tonit Hi Toni, I'll work on getting you synced up!

**Comment by scottrigby** [comment]
> Hi team, congrats for all your work here!
> 
> As shared with Cornelia and Tamao, if you need some help to review CFPs, I would be happy to be with you.
> Best,
> Philippe

Also added you at https://github.com/gitops-working-group/gitops-working-group/issues/105#issuecomment-815262616

I'm thinking we should consolidate these issues since we now have 2 lists
