### ISSUE TITLE
Add Chris Short as GWG YouTube editor

### ISSUE THREAD

**Issue by scottrigby** [gitops-working-group/gitops-working-group#135]
@chris-short is helping with YouTube ninja skills for for GitOpsCon EU 2021 🥷

To be added as a [Manager](https://support.google.com/accounts/answer/7311601?visit_id=637547070832278898-1348615570&p=brand_accounts_managers&rd=1)

- [x] Invite (@scottrigby)
- [x] Accept (@chris-short)

**Comment by scottrigby** [comment]
OK invited. @chris-short plz lmk when you accept 😸

**Comment by chris-short** [comment]
Logged into it yesterday. Thank you!
