### ISSUE TITLE
Rename Gitopscon slack channel to events

### ISSUE THREAD

**Issue by christianh814** [gitops-working-group/gitops-working-group#149]
Currently we have [`#wg-gitops-gitopscon2021`](https://cloud-native.slack.com/archives/C01R2GXGTDL) in the CNCF Slack channel.

We want to rename this to `#wg-gitops-events` since we are going to be using it as general events planning committee slack channel.

**Comment by todaywasawesome** [comment]
Might be easier to just make a new one. We may want to have individual con slack channels sometimes.

**Comment by christianh814** [comment]
> Might be easier to just make a new one. We may want to have individual con slack channels sometimes.

Yeah I'm all for that.

Should the other one be archived or renamed to something else? I leaning towards archived since these sub-committees would be temporary for the event.

**Comment by roberthstrand** [comment]
Archiving works, no reason to have it active after the event.

**Comment by scottrigby** [comment]
Copying [this slack discussion](https://cloud-native.slack.com/archives/C01G9DEE88M/p1621024485090400) to this issue:

> Scott Rigby  4 hours ago
> Hey Christian, so I think we may as well keep the #wg-gitops-gitopscon2021 slack channel, and jsut ask to rename it. There’s no reason I can see to make people who have already joined do extra work for the rename. Any strong opinions about that?
>
> Christian Hernandez  4 hours ago
> +1 on renaming it
> Because yes, that saves us from having to re-invite everyone
> Also anyone who wants to be involved is already there 😄

**Comment by scottrigby** [comment]
I have opened a CNCF Service Desk ticket to ask for the channel rename

**Comment by scottrigby** [comment]
This was done a while ago. Now we are archiving those wg sub-channels, and only keeping `#wg-gitops` and `#opengitops`.

Service desk ticket for ref: https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-999
