### ISSUE TITLE
How to get involved?

### ISSUE THREAD

**Issue by Piotr1215** [gitops-working-group/gitops-working-group#160]
Hi, I'm a cloud architect and devops enthusiast. I have experience mostly in Azure and GCP. Kubernetes, containerization, infrastructure as code with terrafrom etc. I can also create diagrams using PlantUML (check my github profile for some), write C#, F' and Go code. I will soon transition to a different role with much more exposure to GitOps. How can I help/get involved with the GtiOps Working Group?

**Comment by christianh814** [comment]
The best way to get involved is to attend a meeting. 

https://github.com/gitops-working-group/gitops-working-group#how-to-get-involved

Another way is to join the slack channel and ask around

https://cloud-native.slack.com/archives/C01G9DEE88M

**Comment by scottrigby** [comment]
Closing this issue. For future ref, here is the list of ways to get involved – also on opengitops.dev - https://github.com/cncf/tag-app-delivery/blob/main/gitops-wg/README.md#community
