### ISSUE TITLE
"Volunteer" link on README.md is broken

### ISSUE THREAD

**Issue by JaimeMagiera** [gitops-working-group/gitops-working-group#177]
The "Volunteer" link on the README.md is broken (404). The target file is apparently non-existent on that branch.

**Comment by scottrigby** [comment]
Hi @JaimeMagiera Thank you! I'm not sure what you were seeing but the link works in the GitOps WG README new location under the App Delivery TAG repo. Closing this as part of:
- Related to https://github.com/open-gitops/project/issues/2
