### ISSUE TITLE
Getting Involved

### ISSUE THREAD

**Issue by gaughen** [gitops-working-group/gitops-working-group#18]
Hi there - I work at InfluxData.  My manager recently gave a presentation on what we do here with gitops - https://www.cncf.io/webinars/gitops-at-scale-for-a-multi-cloud-multi-region-stateful-application/

I would love to get involved to share what we've learned and learn from others, and to help however I can to make the group a success.

Thanks!
Pat

**Comment by todaywasawesome** [comment]
**Suggestions for participating**: 
- If you haven't already joined the slack it's the [CNCF slack](https://slack.cncf.io/) #wg-gitops
- Add your info to the [interest doc](https://docs.google.com/document/d/11EZfvB2FFI837nMmArnyv-wizsIJvc-4_xdgfoUXF4o/edit)
- Join [upcoming meetings](https://github.com/gitops-working-group/gitops-working-group/blob/main/MEETINGS.md)
