### ISSUE TITLE
Getting Involved

### ISSUE THREAD

**Issue by kesseract** [gitops-working-group/gitops-working-group#24]
I would love to participate in this GitOps working group and contribute whatever I can.

**Comment by todaywasawesome** [comment]
Glad to have you!

**Suggestions for participating**: 
- If you haven't already joined the slack it's the [CNCF slack](https://slack.cncf.io/) #wg-gitops
- Add your info to the [interest doc](https://docs.google.com/document/d/11EZfvB2FFI837nMmArnyv-wizsIJvc-4_xdgfoUXF4o/edit)
- Join [upcoming meetings](https://github.com/gitops-working-group/gitops-working-group/blob/main/MEETINGS.md)
