### ISSUE TITLE
Getting Involved

### ISSUE THREAD

**Issue by tpouyer** [gitops-working-group/gitops-working-group#25]
I'd like to get involved.  I bring years of CI/CD and Deployment Automation experience with me, and a touch of SRE/Operational knowledge.  I'd be keenly interested in helping with "Fleet Management" and "Operational Concerns" and how GitOps could potentially solve those problems.

**Comment by todaywasawesome** [comment]
Awesome! One of the things I'd like to start working on soon is a section of patterns and having one for fleet management is especially interesting. 

**Suggestions for participating**: 
- If you haven't already joined the slack it's the [CNCF slack](https://slack.cncf.io/) #wg-gitops
- Add your info to the [interest doc](https://docs.google.com/document/d/11EZfvB2FFI837nMmArnyv-wizsIJvc-4_xdgfoUXF4o/edit)
- Join [upcoming meetings](https://github.com/gitops-working-group/gitops-working-group/blob/main/MEETINGS.md)
