### ISSUE TITLE
Getting involved

### ISSUE THREAD

**Issue by chris-short** [gitops-working-group/gitops-working-group#26]
I would like to participate in this working group and contribute however I can.

Additionally, I'd like to be able to provide feedback to my peers at Red Hat to drive some standardization and best practices.

**Comment by todaywasawesome** [comment]
Glad to have you @chris-short! I think you're already on the Slack and to the [interest doc](https://docs.google.com/document/d/11EZfvB2FFI837nMmArnyv-wizsIJvc-4_xdgfoUXF4o/edit) so the next thing would be to just join [upcoming meetings](https://github.com/gitops-working-group/gitops-working-group/blob/main/MEETINGS.md).
