### ISSUE TITLE
Getting Involved

### ISSUE THREAD

**Issue by jlarfors** [gitops-working-group/gitops-working-group#27]
Hi, and great work on creating this group!

I would like to be involved in this group and see how/where/what I can contribute.

Personally I am big fan of the GitOps philosophy as it adds a much clearer definition to the "Deployment" when talking CI/CD and creates a nice distinction between Continuous Delivery and Ops.

We already practice this in multiple projects, either through Terraform and infra as code with a traditional *push-based* deployment, or with FluxCD for applications using the *pull-based* deployment method, so also very open to talking with like minded people.

Some of the interesting things that I might be able to contribute with:
- practical working experience with both Kubernetes and Nomad
- involvement in embedded projects, so often GitOps is used as a way to provision a delivery stack (dev tools) not the end product

I already added my name to this list in this document as well, I was not sure exactly on the procedure to follow:
https://docs.google.com/document/d/11EZfvB2FFI837nMmArnyv-wizsIJvc-4_xdgfoUXF4o/edit?usp=sharing

**Comment by todaywasawesome** [comment]
Awesome! Don't forget to join #wg-gitops in the CNCF slack. You can also find info on upcoming meetings here https://github.com/gitops-working-group/gitops-working-group/blob/main/MEETINGS.md

**Comment by jlarfors** [comment]
Thanks for the link and info
