### ISSUE TITLE
Apply for CNCF Sandbox

### ISSUE THREAD

**Issue by monadic** [gitops-working-group/gitops-working-group#32]
By agreement between the initial maintainers, this project is applying for CNCF Sandbox.  The idea is to retain the governance.md model but grow into "it's own project and implementation neutral".  We consider libcni and smi to be prior art.

This issue is filed to record that this process has begun.

**Comment by tonit** [comment]
Projects seems to be created: https://www.cncf.io/sandbox-projects/

**Comment by scottrigby** [comment]
This is ✅  Also see "Name change proposal" #64 discussion.
