### ISSUE TITLE
Reduce number of required signoffs to 1 reviewers

### ISSUE THREAD

**Issue by bricef** [gitops-working-group/gitops-working-group#49]
We currently need 2 maintainers to sign off on any commit. We should relax this to make sure we can go faster.

We can always revert the decision as the WG gets bigger.

**Comment by dj1k** [comment]
I agree. I believe we need another maintainer to second.

**Comment by cdavisafc** [comment]
I agree. Is this all we need to do to make it so? Who can change this config for us. @scottrigby if you can, please go ahead.

**Comment by scottrigby** [comment]
Yes, we agreed in the meeting so this was just a formality. That said, with your +1 we are ready. I have just changed the setting to require 1 owner review only on `main` ✅
