### ISSUE TITLE
Is Apache 2.0 license correct?

### ISSUE THREAD

**Issue by schlomo** [gitops-working-group/gitops-working-group#57]
I noticed that the license here is Apache 2.0 - is this really appropriate for a repo that won't provide code but rather documentation? Maybe CC-BY-SA would be better suited?

**Comment by tonit** [comment]
Question to @cdavisafc and generally current maintainers. It looks like for "demo code" ASL2 is already used elsewhere (looking at the very good potatohead project of the app delivery sig).

**Comment by scottrigby** [comment]
Precedence:

Both Apache 2.0 and CC by 4.0:
- https://github.com/cncf/cnf-wg/blob/master/LICENSE.md

Apache 2.0 only:
- https://github.com/cncf/wg-ci/blob/master/LICENSE
- https://github.com/cncf/wg-serverless/blob/master/LICENSE
- https://github.com/cncf/wg-networking/blob/master/LICENSE
- https://github.com/cncf/udpa/blob/main/LICENSE
