### ISSUE TITLE
Need logo

### ISSUE THREAD

**Issue by schlomo** [gitops-working-group/gitops-working-group#61]
We need a logo

**Comment by tonit** [comment]
On slack there was the very promising contribution from slack user "iboonox" https://cloud-native.slack.com/files/UEB4FKKNF/F01NM732QUW/logo1.png in the GitOps Channel:
![image](https://user-images.githubusercontent.com/67375/109131305-f5cfec00-7752-11eb-992d-cf2b010f5b4c.png)

**Comment by scottrigby** [comment]
+1 for getting the logo sorted. Let's create a GitHub discussion in the proposal category for this. Could the designer do this, would one of you like to, or would you prefer I do this and loop everyone in there?

**Comment by schlomo** [comment]
#63 is the discussion

**Comment by scottrigby** [comment]
Completed in https://github.com/gitops-working-group/gitops-working-group/pull/124
