### ISSUE TITLE
How about gitops cli tool ?

### ISSUE THREAD

**Issue by vijaySamanuri** [gitops-working-group/gitops-working-group#7]
We have several environment stages at our place but `gitops` doesn't cover the promotion part among these stages.
As a workaround we adopted "branch per environment" strategy and rotating the PR to the other environment but these all are manual steps and when we script this to CI system its all non standard i.e different CI system requires different way of doing it for example github actions requires different way of doing it, gitlab plugin different way.

I think it is beneficial to have a standard cli tool something like `gitops` which deals with all the manual steps during the gitops deployment process. This tool just interacts with the underlying git tool and wraps the gitops specific git commands.

for example:

`gitops init hld --for-app=guestbook` would initiate the HLD repository if not present
`gitops env add stage` would create a `stage` branch in HLD repository
`gitops raisePR prod --from=stage` raises a PR from `stage` branch to `prod` branch
`gitops rollback prod`
etc

**Comment by ams0** [comment]
Isn't the whole point of `GitOps` to manage infrastructure and applications via `git`? Is it not then that you really only need:

```console
git init
git branch staging
gh pr create #Github CLI
git reset --soft HEAD~1
```
?

**Comment by scottrigby** [comment]
I'd suggest re-opening this as a discussion topic now that #36 is set up. I'd convert it for you, but for the moment we can't due to https://github.com/github/feedback/discussions/2924#discussioncomment-254592.

**Comment by tonit** [comment]
I agree with @ams0 that "pull request driven operations" really seem to be the theme around gitops. 

Still i can imagine that imperative CLI tools have its place when carefully crafting/shaping pull requests. 

Similar to tooling around GitFlow you want to automate most (boring) tasks such as templating a (common) change, testing,  managing potential dependencies between PRs etc.

WDYT?
