### ISSUE TITLE
Make scottrigby org owner

### ISSUE THREAD

**Issue by scottrigby** [gitops-working-group/gitops-working-group#72]
As a Member I've set up [projects at the org level](https://github.com/orgs/gitops-working-group/projects) as promised (see action items in [March 11, 2021 meeting notes](https://docs.google.com/document/d/1hxifmCdOV5_FbKloDJRWZQHq0ge-trXJKF-BgV4wHVk/edit#heading=h.7g5ep31z1bvg)). However I can't delegate access for other people to help organize to those projects without [Owner](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/permission-levels-for-an-organization) status.

**Comment by bricef** [comment]
Done.
