### ISSUE TITLE
Move github.com/gitops-working-group/gitops-working-group to github.com/cncf/gitops-wg

### ISSUE THREAD

**Issue by scottrigby** [gitops-working-group/gitops-working-group#73]
Other WG examples:

- https://github.com/cncf/cnf-wg
- https://github.com/cncf/wg-ci
- https://github.com/cncf/wg-serverless
- https://github.com/cncf/wg-networking
- https://github.com/cncf/udpa

**Comment by roberthstrand** [comment]
Seems logical enough, there's no need for an entire organization for one working group.

**Comment by scottrigby** [comment]
I talked with Chris A about this, and CNCF prefers keeping only CNCF staff projects under GitHub.com/cncf, and recommends other WGs and projects to otherwise set up their own top level org as needed. So we're good with the WG GitHub org as-is after all.
