### ISSUE TITLE
Working Group Work Product Name Suggestion "GitOps Commitments"

### ISSUE THREAD

**Issue by tpouyer** [gitops-working-group/gitops-working-group#8]
There has been some discussion around the use of the word "manifesto" and the connotations that word might bring with it.  There was a comment in one of the Google Docs but I can't find it now, and it was brought up during the first meeting of the working group on Dec 10.

I wanted to make a suggestion for a name of the work product of this group:

__"GitOps Commitments"__

I believe it's a fun name that expresses the _intent_ of the work product of this working group.

**Comment by todaywasawesome** [comment]
Just adding notes from the discussion in the meeting. Other alternatives proposed:

- Declaration
- Pillars
- 12-factor  or using “no label”
- Whitepaper

**Comment by bricef** [comment]
There's a history of using "Principles" to discuss GitOps dating back a couple of years now. It seems that this would be the least complex term to use, and would enable good discoverability when searching for information.

**Comment by jlbutler** [comment]
> There's a history of using "Principles" to discuss GitOps dating back a couple of years now. It seems that this would be the least complex term to use, and would enable good discoverability when searching for information.

This also works purely around terminology, where a principle is a defined truth that serves as foundational to a set of beliefs.

**Comment by scottrigby** [comment]
Thanks @tpouyer and everyone for the suggestions. Per working group meetings, this is currently being worked on in #38 as "Principles". Closing this issue in favor of that PR. BTW there are live sync sessions on the Principles planned to start next week, follow that PR for updates.

If anyone wants to discuss the name further, please open a [discussion](https://github.com/gitops-working-group/gitops-working-group/discussions) proposal.
