### ISSUE TITLE
Provisional logo for media around GitOpsCon EU 2021

### ISSUE THREAD

**Issue by scottrigby** [gitops-working-group/gitops-working-group#82]
A task for #69 

See WIP #63 

Thank you @iboonox for the quick help on this

**Comment by iboonox** [comment]
![cocon](https://user-images.githubusercontent.com/1584813/111710468-0b17d200-884a-11eb-9a0e-cbd8d477d51f.png)

**Comment by iboonox** [comment]
![cocon](https://user-images.githubusercontent.com/1584813/111710582-3b5f7080-884a-11eb-8a8f-8b9c936977e6.png)

**Comment by scottrigby** [comment]
Looking great for now! 

CFP:

<img width="676" alt="Screen Shot 2021-03-19 at 4 04 15 PM" src="https://user-images.githubusercontent.com/407675/111836492-c2edc380-88cc-11eb-9048-09affca3bdad.png">


Twitter:

<img width="621" alt="Screen Shot 2021-03-19 at 4 14 14 PM" src="https://user-images.githubusercontent.com/407675/111837378-2fb58d80-88ce-11eb-9267-c5c220c8f0c8.png">


GitHub:

<img width="792" alt="Screen Shot 2021-03-19 at 4 15 26 PM" src="https://user-images.githubusercontent.com/407675/111837475-52e03d00-88ce-11eb-84ec-84848f909659.png">
