### ISSUE TITLE
Confirm maintainers have read "Services for CNCF projects"

### ISSUE THREAD

**Issue by scottrigby** [gitops-working-group/gitops-working-group#94]
As part of project onboarding https://github.com/cncf/toc/issues/584, we need to confirm maintainers have read [Services for CNCF projects](https://www.cncf.io/services-for-projects/).

This is the current list of maintainers. Please respond when you have read the services page 👀 

- [x] Chris Patterson, GitHub @chrispat
- [x] Chris Sanders, Microsoft @csand-msft
- [x] Dan Garfield, Codefresh @todaywasawesome
- [x] Jesse Butler, Amazon Web Services @jlbutler
- [x] Leonardo Murillo @murillodigital
- [x] Scott Rigby, Weaveworks @scottrigby

Previously. See https://github.com/gitops-working-group/gitops-working-group/pull/136
~- [ ] Nathan Taber, Amazon Web Services @tabern~
~- [x] Daniel Lizio-Katzen, Weaveworks @dj1k~

**Comment by dj1k** [comment]
I confirm that I've read the services page.

**Comment by csand-msft** [comment]
Confirm

**Comment by jlbutler** [comment]
I have read the Services page, thanks!

**Comment by murillodigital** [comment]
I confirm I've read the service for cncf projects page.

**Comment by chrispat** [comment]
I confirm I've read the service for CNCF projects page
